src/renderer/features/screens/editor/index.tsx
src/renderer/features/screens/start/index.tsx

This PR resolve #31 issue.
- Create a dummy function to navigate from the start screen to the editor.

Feat #31 - Add mock function to handle the screen management

---

src/renderer/features/screens/start/components/display-recent-projects/elements/wrapper/index.tsx
src/renderer/features/screens/start/index.tsx

This PR doesn't refers to any issue.
- Fix the menu bottom space

Hotfix - Fix spacing of menu

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/test.yml
src/renderer/index.tsx

This PR resolve the #38 issue.
- Create actions for workflow

Feat #38 - Create continuous integration pipeline 

---

src/renderer/features/screens/start/index.tsx
src/renderer/features/screens/workspace/components/activitybar/components/button.tsx
src/renderer/features/screens/workspace/components/activitybar/components/index.ts
src/renderer/features/screens/workspace/components/activitybar/index.tsx
src/renderer/providers/router-provider.tsx

- Refactor the activity bar
- Fix the route handler flow

Fix - Fix the route handler flow

---

package-lock.json
src/main/main.ts
src/renderer/features/layout.tsx
src/renderer/features/screens/start/components/actions-bar/index.tsx
src/renderer/features/screens/start/components/display-example-projects/index.tsx
src/renderer/index.ejs
src/renderer/styles/globals.css

- Add personalized experience using titlebar for Linux user

Fix - Refactor titlebar

---

src/renderer/features/editors/textual/config/themes/open-plc/openplc.ts
src/renderer/features/screens/start/index.tsx
src/renderer/features/screens/workspace/components/panels/editor-panel/variable-table/index.tsx
src/renderer/features/screens/workspace/components/panels/editor-panel/variable-table/table/elements/header.tsx
src/renderer/features/screens/workspace/components/panels/navigation-panel/index.tsx
src/renderer/features/screens/workspace/components/panels/navigation-panel/tabs/index.tsx
tailwind.config.ts

- Repair start screen files to show
- Fix blue line on top of tabs
- Fix editor background and number colors
- Fix variable table text styles

Fix - Repair visual issues

---

src/renderer/components/_atoms/button/index.tsx
src/renderer/components/_atoms/card/index.tsx
src/renderer/components/_atoms/file/index.tsx
src/renderer/components/_atoms/index.ts
src/renderer/components/_atoms/input/index.tsx
src/renderer/components/_features/[start]/menu/index.tsx
src/renderer/components/_molecules/search/index.tsx
src/renderer/components/_organisms/panel/index.tsx
src/renderer/components/_templates/[start]/index.ts
src/renderer/components/_templates/[start]/main-content.tsx
src/renderer/components/_templates/[start]/side-content.tsx
src/renderer/components/_templates/[workspace]/index.ts
src/renderer/components/_templates/[workspace]/main-content.tsx
src/renderer/components/_templates/[workspace]/side-content.tsx
src/renderer/components/_templates/app-layout.tsx
src/renderer/components/_templates/index.ts
src/renderer/components/elements/card/card-root.tsx
src/renderer/features/screens/start/index.tsx
src/renderer/features/screens/workspace/components/activitybar/index.tsx
src/renderer/features/screens/workspace/components/main-content/index.tsx

Fix - Refactor folder structure

---

src/renderer/components/_features/[workspace]/create-pou/card.tsx
src/renderer/components/_molecules/project-tree/index.tsx
src/renderer/components/_molecules/tabs/index.tsx
src/renderer/components/_organisms/explorer/project.tsx
src/renderer/store/slices/tabs-slice.ts

- Update the tabs slice schema
- Refactor the handle create tab function

Refactor - Update the tabs slice store

---

src/renderer/components/_atoms/table/index.tsx
src/renderer/components/_molecules/variables-table/editable-cell.tsx
src/renderer/components/_molecules/variables-table/index.tsx
src/renderer/components/_molecules/variables-table/selectable-cell.tsx

- Variable Table
- Add click to select the row
- To edit the inputs, the row have to be selected
- Add visual feedback when input is focused
- Add border to text area at documentation

Feat: Add selectable row

---

src/renderer/components/_molecules/variables-table/editable-cell.tsx
src/renderer/components/_molecules/variables-table/index.tsx
src/renderer/components/_molecules/variables-table/selectable-cell.tsx
src/renderer/components/_organisms/variables-editor/index.tsx
src/renderer/store/index.ts
src/renderer/store/slices/index.ts
src/renderer/store/slices/workspace/index.ts
src/renderer/store/slices/workspace/slice.ts
src/renderer/store/slices/workspace/types.ts
src/types/PLC/test.ts

Add functions to variables table
- Add, remove, update/change, rearrange variables

Feat: Add variables to store

---

src/renderer/components/_features/[workspace]/editor/monaco/index.tsx
src/renderer/components/_molecules/charts/line-chart.tsx
src/renderer/components/_molecules/project-tree/index.tsx
src/renderer/components/_molecules/variables-table/index.tsx
src/renderer/components/_organisms/explorer/project.tsx
src/renderer/components/_organisms/variables-editor/index.tsx
src/renderer/components/_templates/[workspace]/main-content.tsx
src/renderer/features/titlebar/menu-bar.tsx
src/renderer/features/titlebar/titlebar-center-content.tsx
src/renderer/features/titlebar/titlebar-left-content.tsx
src/renderer/features/titlebar/titlebar-right-content/index.tsx
src/renderer/screens/workspace-screen.tsx
src/renderer/store/slices/workspace/slice.ts
src/renderer/store/slices/workspace/types.ts
src/types/PLC/open-plc.ts

Refactor of types at workspace slice

Fix: Refactor workspace

---

src/renderer/components/_atoms/table/index.tsx
src/renderer/components/_features/[workspace]/create-element/element-card/index.tsx
src/renderer/components/_molecules/tabs/index.tsx
src/renderer/components/_molecules/variables-table/editable-cell.tsx
src/renderer/components/_molecules/variables-table/index.tsx
src/renderer/components/_organisms/explorer/project.tsx
src/renderer/components/_organisms/variables-editor/index.tsx
src/renderer/store/slices/editor/slice.ts
src/renderer/store/slices/editor/types.ts
src/renderer/store/slices/shared/index.ts
src/renderer/store/slices/shared/utils/index.ts
src/renderer/store/slices/tabs/utils.ts
src/renderer/store/slices/workspace/slice.ts
src/renderer/store/slices/workspace/types.ts
src/renderer/store/slices/workspace/utils/variables.ts

Refactor at editor slices and variables table to make it singular for each pou opened

Fix: Refactor global store

---

src/renderer/components/_atoms/table/index.tsx
src/renderer/components/_molecules/variables-table/index.tsx
src/renderer/store/slices/editor/slice.ts

Editor bug when click at explorer reseting editor state.
Responsibility of selected borders to variables-table molecule function (setBorders)

Fix: editor bug

---

src/renderer/components/_atoms/react-flow/index.tsx
src/renderer/components/_molecules/rung/body.tsx
src/renderer/components/_organisms/rung/index.tsx

[LEC-79](https://linear.app/lecode/issue/LEC-79/create-canvas-element)
**_The code might break, this is concept_**
- Create the basic behaviour of the react flow to ladder language
- Horizontal scroll
- Div grow when reactflow viewport grow

FEAT: Create LD worksheet

---

package-lock.json
package.json
src/renderer/assets/icons/interface/ArrowButton.tsx
src/renderer/components/_features/[workspace]/editor/graphical/elements/arrow-button-group/index.tsx
src/renderer/components/_features/[workspace]/editor/graphical/elements/block/index.tsx
src/renderer/components/_features/[workspace]/editor/graphical/elements/contact/index.tsx
src/renderer/components/_molecules/library-tree/index.tsx
src/renderer/styles/globals.css

- Fix the width of block element modal 
- Create the increment and decrement function for inputs
- Create the filter on library files

Fix - Refactor block modal

---

src/renderer/components/_atoms/react-flow/custom-nodes/handle.tsx
src/renderer/components/_atoms/react-flow/custom-nodes/index.ts
src/renderer/components/_atoms/react-flow/custom-nodes/mock-node.tsx
src/renderer/components/_atoms/react-flow/custom-nodes/power-rail.tsx
src/renderer/components/_molecules/rung/body.old
src/renderer/components/_molecules/rung/body.tsx
src/renderer/components/_molecules/rung/utils.ts
src/renderer/components/_organisms/rung/index.tsx

[LEC-90](https://linear.app/lecode/issue/LEC-90/set-rung-worksheet-bounds)
- Create power rail nodes
- Create utils functions to control the ladder flow ( [SERIAL ONLY](https://www.electricaltechnology.org/2020/05/difference-between-series-parallel-circuit.html) )
- Add nodes at correct position
- Redimension the flow and change the right power rail position to make it fixed at the end of the bound

FEAT: Create rung worksheet bounds

---

src/renderer/components/_features/[workspace]/editor/graphical/ladder/index.tsx
src/renderer/components/_features/[workspace]/editor/search-in-project/index.tsx
src/renderer/screens/workspace-screen.tsx

- Create the modal to search in project
- Add functionality to render the modal "search in project" when click on search icon in activity bar

Feat - Create search in project

---

src/renderer/assets/icons/flow/Contact.tsx
src/renderer/components/_atoms/react-flow/custom-nodes/block.tsx
src/renderer/components/_atoms/react-flow/custom-nodes/contact.tsx
src/renderer/components/_atoms/react-flow/custom-nodes/index.ts
src/renderer/components/_molecules/rung/body.tsx
src/renderer/components/_molecules/rung/ladder-utils.ts

*[LEC-95](https://linear.app/lecode/issue/LEC-95/create-contact-element)*

Feat: Create contact element

---

src/renderer/components/_atoms/workspace-activity-bar/divider.tsx
src/renderer/components/_molecules/rung/body.tsx
src/renderer/components/_molecules/rung/ladder-utils/nodes.ts
src/renderer/components/_molecules/workspace-activity-bar/default/debugger.tsx
src/renderer/components/_molecules/workspace-activity-bar/default/download.tsx
src/renderer/components/_molecules/workspace-activity-bar/default/exit.tsx
src/renderer/components/_molecules/workspace-activity-bar/default/index.ts
src/renderer/components/_molecules/workspace-activity-bar/default/play.tsx
src/renderer/components/_molecules/workspace-activity-bar/default/search.tsx
src/renderer/components/_molecules/workspace-activity-bar/default/transfer.tsx
src/renderer/components/_molecules/workspace-activity-bar/default/zoom.tsx
src/renderer/components/_molecules/workspace-activity-bar/ladder/block.tsx
src/renderer/components/_molecules/workspace-activity-bar/ladder/coil.tsx
src/renderer/components/_molecules/workspace-activity-bar/ladder/contact.tsx
src/renderer/components/_molecules/workspace-activity-bar/ladder/index.ts
src/renderer/components/_molecules/workspace-activity-bar/ladder/loop.tsx
src/renderer/components/_organisms/workspace-activity-bar/default.tsx
src/renderer/components/_organisms/workspace-activity-bar/index.tsx
src/renderer/components/_organisms/workspace-activity-bar/ladder-toolbox.tsx
src/renderer/screens/workspace-screen.tsx

*[LEC-104](https://linear.app/autonomylogic/issue/LEC-104/integrate-the-toolbox-component-with-the-ladder-editor-nodes)*

Feat: Integrate toolbox ladder

---

src/renderer/components/_atoms/react-flow/custom-nodes/index.ts
src/renderer/components/_atoms/react-flow/custom-nodes/parallel.tsx
src/renderer/components/_atoms/react-flow/custom-nodes/placeholder.tsx
src/renderer/components/_molecules/rung/body.tsx
src/renderer/components/_molecules/rung/ladder-utils/edges.ts
src/renderer/components/_molecules/rung/ladder-utils/elements.ts
src/renderer/components/_molecules/rung/ladder-utils/nodes.ts
src/renderer/components/_organisms/workspace-activity-bar/ladder-toolbox.tsx

*[LEC-96](https://linear.app/autonomylogic/issue/LEC-96/create-parallel-element)*
*[LEC-109](https://linear.app/autonomylogic/issue/LEC-109/create-placeholder-element)*
- Change how the parallel block is created
- Added placeholders on all blocks to have the reference and correct location to place a new block
- Create utilitary function to rearrange the parallels and blocks inside them
- Create utilitary function to remove empty parallel
- Inside an parallel connection, remove serial and parallel empty connections
- Refactor `addNewElement` utilitary function
- Check if the new created block is a parallel or a serial
- If it is an parallel (`parallelPlaceholder`), create the parallel block, reorder the related block to be serial with parallel node and, finally, add the new block beeing …

FEAT: Parallell functios

---

src/types/PLC/library.ts

*[LEC-124](https://linear.app/autonomylogic/issue/LEC-124/create-the-shape-for-function-libraries-in-the-application-global)*
- Add property to handle the function type library.
- [ X ] The code is complete and according to developers’ standards.
- [ X ] I have performed a self-review of my code.
- [ X ] Meet the acceptance criteria.
- [ X ] Changes were communicated and updated in the ticket description.

FEAT - Create function library schema

---

src/renderer/components/_features/[workspace]/editor/graphical/elements/coil/index.tsx
src/renderer/components/_features/[workspace]/editor/graphical/elements/contact/index.tsx
src/renderer/components/_molecules/modal/index.tsx
src/renderer/components/_molecules/rung/body.tsx
src/renderer/components/_molecules/rung/ladder-utils/elements.ts

*[LEC-149](https://linear.app/autonomylogic/issue/LEC-149/add-the-functionality-to-manage-the-coil-properties)*
*[LEC-150](https://linear.app/autonomylogic/issue/LEC-150/add-the-functionality-to-manage-the-contact-properties)*
- Coil
- Contact

Feat: link modal to coil and contact

---

src/renderer/components/_features/[workspace]/editor/monaco/drag-and-drop/st.ts
src/renderer/components/_features/[workspace]/editor/monaco/index.tsx
src/renderer/components/_molecules/rung/body.tsx
src/renderer/components/_organisms/explorer/library.tsx

- Add new text/plain channel to library
- Filter the new channel to pass the correct information
- create parsePouToStText function

FEAT: link library to create ST function block

---

src/types/PLC/language-data/ladder-diagram.ts

This PR resolve the *#issue_number*.
*[linear task](link to linear)*
- ...
- ...

FEAT: Parse ladder xml

---

src/renderer/components/_features/[start]/new-project/steps/first-step.tsx
src/renderer/components/_features/[start]/new-project/steps/second-step.tsx
src/renderer/components/_features/[start]/new-project/steps/third-step.tsx

Fix visual issues modal create project

---

src/renderer/components/_atoms/react-flow/custom-nodes/block.tsx
src/renderer/components/_atoms/react-flow/custom-nodes/variable.tsx
src/utils/PLC/language/ladder-xml.ts

- fix: bug syncing the variable name with the block
- fix: empty variable at block
- fix: wrong variable connection @ xml parse

LEC-163: Hotfix fixing bugs

---

src/renderer/components/_molecules/workspace-activity-bar/default/download.tsx
src/renderer/components/_organisms/explorer/project.tsx

This PR resolve the *#issue_number*.
*[linear task](link to linear)*
- ...
- ...

:adhesive_bandage: add temporary code

---

src/main/services/project-service/utils/create-project.ts
src/main/services/project-service/utils/read-project.ts
src/renderer/store/slices/project/slice.ts
src/renderer/store/slices/project/types.ts
src/renderer/store/slices/shared/index.ts
src/types/IPC/project-service/create-project.ts
src/types/IPC/project-service/index.ts
src/types/IPC/project-service/read-project.ts

*[DOPE-92: Create project with the new structure](https://autonomylogic.atlassian.net/browse/DOPE-92)*
- Create project adding the 'main' POU to the correct file path
- Enhance open and create functions to parse separately the POUs
1. Create a new project and check if the filesystem will be similar to this:
_Disclaimer: we cannot save the project and create/delete new pous. Those are the next steps, so check if any of these are merged:_
> _[DOPE-97: Create pous](https://autonomylogic.atlassian.net/browse/DOPE-97)_
> _[DOPE-94: Save project](https://autonomylogic.atlassian.net/browse/DOPE-94)_
> _[DOPE-95: Save file](https://autonomylogic.atlassian.net/browse/DOPE-95)_
[DOPE-94]: https://autonomylogic.atlassian.net/browse/DOPE-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …

DOPE-92: Create project with the new structure
